import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout/Layout'
import { useAccount, useSigner, useProvider } from 'wagmi'
import { Text, Flex, Button, Card } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import { useEffect, useState } from 'react'
import { ethers } from 'ethers'
import { contractAddress, contractX, contractStaking, abi, abiX, abiStaking } from "../public/constants"
import Link from 'next/link';


export default function Collection() {

  const [nftList, setNftList] = useState([]);
  const [uri, setUri] = useState([]);
  const [nftStaked, setNftStaked] = useState([]);
  const [stakedUri, setStakedUri] = useState([]);



  const { address, isConnected } = useAccount()
  const provider = useProvider()
  const { data: signer } = useSigner()
  const [price, setPrice] = useState(0.01);
  const [approval, setApproval] = useState(false);
  const [balance, setBalance] = useState();
  const [reward, setReward] = useState(0);


  const handleChange = (event) => {
    setPrice(event.target.value);
  };

  async function fetchNfts() {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      const nfts = await contract.getMyNFTs();

      setNftList(nfts);
    }
  }

  async function getUrl() {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      const url = []
      for (let i = 0; i < nftList.length; i++) {
        let uri = await contract.tokenURI(nftList[i][3])
        url.push(uri);
      }
      setUri(url)
    }
  }

  async function isApproved() {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      const boolResponse = await contract.isApprovedForAll(address, contractStaking);
      setApproval(boolResponse);
    }
  }

  async function fetchStake() {
    if (isConnected) {
      const staking = new ethers.Contract(contractStaking, abiStaking, signer)
      const stake = await staking.getStaked();
      setNftStaked(stake)
    }
  }

  async function getStakedUrl() {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      const url = []
      for (let i = 0; i < nftStaked.length; i++) {
        let uri = await contract.tokenURI(nftStaked[i][0])
        url.push(uri);
      }
      setStakedUri(url)
    }
  }

  useEffect(() => {
    fetchNfts();
    getUrl()
    isApproved()
    fetchStake()
    getStakedUrl()
    balanceOfUser()
  }, [address, nftList, uri, approval]);

  async function setForSale(id, price) {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      await contract.setForSale(parseInt(id), price);
    }
  }

  async function unSale(id) {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      await contract.unSale(parseInt(id));
    }
  }

  async function staking(id) {
    if (isConnected) {

      const staking = new ethers.Contract(contractStaking, abiStaking, signer)
      await staking.Stake(id);
    }
  }

  async function unstaking(id) {
    if (isConnected) {

      const staking = new ethers.Contract(contractStaking, abiStaking, signer)
      await staking.unstake(id);
    }
  }

  async function claim(id) {
    if (isConnected) {

      const staking = new ethers.Contract(contractStaking, abiStaking, signer)
      await staking.claim(id);
    }
  }

  async function balanceOfUser() {
    if (isConnected) {
      const contractToken = new ethers.Contract(contractX, abiX, signer)
      const amount = await contractToken.balanceOf(address);
      setBalance(ethers.utils.formatEther(amount.toString()))
    }
  }

  async function approveUser() {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      await contract.setApprovalForAll(contractStaking, true);
    }
  }


  return (
    <>
      <Head>
        <title>Shambles : My Shambles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isConnected ? (
          <div className="App">
            <h1>My NFTs / Tokens balance: {balance}</h1>
            {nftStaked.map((nft, index) => (
              < div key={nft[0]} >
                < Image src={stakedUri[index]} alt="img" width={400} height={400} style={{ margin: 10 }} />
                <Card style={{ margin: 20, padding: 10, border: `10px solid ${nft[0] ? "green" : "red"}` }} key={nft[0]}>
                  id#{nft[0]}
                  <Button style={{
                    color: "#F9DC5C",
                    backgroundColor: "blue",
                    padding: 10,
                    margin: 10,
                    transition: "background-color 0.3s ease",
                    borderRadius: 5,
                    textDecoration: "none"
                  }} onClick={() => claim(nft[0])}>Claim Reward</Button>

                  {address != nft[2] ?
                    <p> owner: 0x...{nft[2].slice(-4)}</p>
                    : <div className="text-emerald-700">You are the owner of this NFT</div>
                  }
                  <Button style={{
                    color: "#F9DC5C",
                    backgroundColor: "blue",
                    padding: 10,
                    margin: 10,
                    transition: "background-color 0.3s ease",
                    borderRadius: 5,
                    textDecoration: "none"
                  }} onClick={() => unstaking(nft[0])}>Unstake NFT</Button>
                </Card>
                <hr></hr>
              </div>
            ))}
            {nftList.map((nft, index) => (
              < div key={nft[3]} >
                < Image src={uri[index]} alt="img" width={400} height={400} style={{ margin: 10 }} />
                <Card style={{ margin: 20, padding: 10, border: `10px solid ${nft[0] ? "green" : "red"}` }} key={nft[3]}>
                  id#{nft[3]}

                  {address != nft[2] ?
                    <p> owner: 0x...{nft[2].slice(-4)}</p>
                    : <div className="text-emerald-700">You are the owner of this NFT</div>
                  }
                  <p>Token for Sale: {nft[0].toString()}
                    {nft[0] == false ? (
                      <div>
                        <input
                          style={{ border: "1px solid black" }}
                          type="number"
                          step="0.01"
                          min="0.01"
                          value={price}
                          onChange={handleChange}
                        />

                        <Button style={{
                          color: "#F9DC5C",
                          backgroundColor: "green",
                          padding: 10,
                          margin: 10,
                          transition: "background-color 0.3s ease",
                          borderRadius: 5,
                          textDecoration: "none"
                        }} onClick={() => setForSale(nft[3], price * 100)}>Set ForSale</Button>
                      </div>) :
                      (<Button style={{
                        color: "#F9DC5C",
                        backgroundColor: "red",
                        padding: 10,
                        margin: 10,
                        transition: "background-color 0.3s ease",
                        borderRadius: 5,
                        textDecoration: "none"
                      }} onClick={() => unSale(nft[3])}>Set UnSale</Button>)}
                  </p>
                  {approval ? (<Button style={{
                    color: "#F9DC5C",
                    backgroundColor: "blue",
                    padding: 10,
                    margin: 10,
                    transition: "background-color 0.3s ease",
                    borderRadius: 5,
                    textDecoration: "none"
                  }} onClick={() => staking(nft[3])}>Stake NFT</Button>)
                    :
                    (<Button style={{
                      color: "#F9DC5C",
                      backgroundColor: "blue",
                      padding: 10,
                      margin: 10,
                      transition: "background-color 0.3s ease",
                      borderRadius: 5,
                      textDecoration: "none"
                    }} onClick={() => approveUser()}>Approve for NFT Staking</Button>)}

                </Card>
                <p>Token Price: {ethers.utils.formatEther(nft[1].toString())} eth</p>
                <hr></hr>
              </div>
            ))}
          </div>
        ) : (
          <Alert status='warning' width="50%">
            <Image src="/gif.gif" alt="logo" width={40} height={40} style={{ margin: 10 }} display={{ base: 'none', md: 'block' }} />
            <AlertIcon />
            Please, connect your Wallet!
          </Alert>
        )}
      </Layout>
    </>
  )
}
