import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout/Layout'
import BigNFTSlider from '@/components/BigNFTSlider/BigNFTSlider'
import { useAccount, useProvider, useSigner } from 'wagmi'
import {
  Text, Flex, Button, Card, Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuItemOption,
  MenuGroup,
  MenuOptionGroup,
  MenuDivider
} from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import { useEffect, useState } from 'react'
import { ethers } from 'ethers'
import { contractAddress, abi } from "../public/constants"

export default function Home() {

  const { address, isConnected } = useAccount()
  const [nftList, setNftList] = useState([]);
  const { data: signer } = useSigner();
  const [uri, setUri] = useState([]);

  async function fetchNfts() {
    const contract = new ethers.Contract(contractAddress, abi, signer)
    const nfts = await contract.getAllNFTs();

    setNftList(nfts);
  }

  useEffect(() => {
    fetchNfts();
    getUrl()
  }, [address, signer, nftList, uri]);

  async function getUrl() {
    const contract = new ethers.Contract(contractAddress, abi, signer)
    const url = []
    for (let i = 0; i < nftList.length; i++) {
      let uri = await contract.tokenURI(nftList[i][3])
      url.push(uri);
    }
    setUri(url)
  }

  return (
    <>
      <Head>
        <title>Shambles DApp : Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <BigNFTSlider />
      </Layout>
    </>
  )
}
