import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout/Layout'
import { useAccount, useSigner, useProvider } from 'wagmi'
import { Text, Flex, Button, Card } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import { useEffect, useState, useCallback } from 'react'
import { ethers } from 'ethers'
import { contractAddress, abi } from "../public/constants"
import Link from 'next/link';
import Style from "../components/BigNFTSlider/BigNFTSlider.module.css";

import { MdVerified, MdTimer } from "react-icons/md";
import { TbArrowBigLeftLines, TbArrowBigRightLine } from "react-icons/tb";

import Countdown from "react-countdown";
import { id } from 'ethers/lib/utils.js'


export default function Collection() {

  const [nftList, setNftList] = useState([]);
  const [uri, setUri] = useState([]);

  const [idNumber, setIdNumber] = useState(0);
  const { address, isConnected } = useAccount()
  const provider = useProvider()
  const { data: signer } = useSigner()
  const [countdownTimestamp, setCountdownTimestamp] = useState(0);
  const [timeRemaining, setTimeRemaining] = useState(0);

  async function fetchNfts() {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      const nfts = await contract.getAllNFTs();

      setNftList(nfts);
    }
  }

  async function getUrl() {
    if (isConnected) {
      const contract = new ethers.Contract(contractAddress, abi, signer)
      const url = []
      for (let i = 0; i < nftList.length; i++) {
        let uri = await contract.tokenURI(nftList[i][3])
        url.push(uri);
      }
      setUri(url)

    }
  }

  async function getTimestamp() {
    if (isConnected) {
      setCountdownTimestamp(parseInt(nftList[idNumber][5]));
    }
  }

  useEffect(() => {
    fetchNfts();
    getUrl()
    getTimestamp()
    const interval = setInterval(() => {
      const currentTime = Math.floor(Date.now() / 1000);
      const remaining = countdownTimestamp - currentTime;
      if (remaining >= 0) {
        setTimeRemaining(remaining);
      } else {
        setTimeRemaining(0);
        clearInterval(interval); // Arrêter l'intervalle une fois que le compte à rebours est terminé
      }
    }, 1000);
  }, [address, nftList, uri, idNumber]);


  const inc = useCallback(() => {
    if (idNumber + 1 < nftList.length) {
      setIdNumber(idNumber + 1);
    }
  }, [idNumber, nftList.length]);

  const dec = useCallback(() => {
    if (idNumber > 0) {
      setIdNumber(idNumber - 1);
    }
  }, [idNumber]);

  const rendererHours = ({ hours }) => {
    // Render the countdown components
    return (
      <span>{hours}</span>
    )
  }

  const rendererMinutes = ({ minutes }) => {
    // Render the countdown components
    return (
      <span>{minutes}</span>
    )
  }

  const rendererSecondes = ({ seconds }) => {
    // Render the countdown components
    return (
      <span>{seconds}</span>
    )
  }

  return (
    <>
      <Head>
        <title>Shambles : Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isConnected && nftList.length > 0 ? (
          <div className="App">
            <div className={Style.bigNFTSlider}>
              <div className={Style.bigNFTSlider_box}>
                <div className={Style.bigNFTSlider_box_left}>


                  <div className={Style.bigNFTSlider_box_left_bidding}>
                    <div className={Style.bigNFTSlider_box_left_bidding_box}>
                      <small>Current Bid</small>
                      <p>
                        {(ethers.utils.formatEther(nftList[idNumber][7].toString()))} <span>eth</span>
                      </p>
                      <small>highest Bidder</small>
                      <p>{nftList[idNumber][6].toString()}</p>
                    </div>

                    <p className={Style.bigNFTSlider_box_left_bidding_box_auction}>
                      <MdTimer
                        className={Style.bigNFTSlider_box_left_bidding_box_icon}
                      />
                      <span>Auction ending at {new Date(nftList[idNumber][5] * 1000).toLocaleDateString()} {new Date(nftList[idNumber][5] * 1000).toLocaleTimeString()}</span>
                    </p>
                    {timeRemaining == 0 ? (<p>Auction is over</p>) : (


                      <div className={Style.bigNFTSlider_box_left_bidding_box_timer}>
                        <div
                          className={Style.bigNFTSlider_box_left_bidding_box_timer_item}
                        >
                          <p>
                            <Countdown date={Date.now() + timeRemaining * 1000} renderer={rendererHours} />
                          </p>
                          <span>Hours</span>
                        </div>

                        <div
                          className={Style.bigNFTSlider_box_left_bidding_box_timer_item}
                        >
                          <p>
                            <Countdown date={Date.now() + timeRemaining * 1000} renderer={rendererMinutes} />
                          </p>
                          <span>mins</span>
                        </div>

                        <div
                          className={Style.bigNFTSlider_box_left_bidding_box_timer_item}
                        >
                          <p>
                            <Countdown date={Date.now() + timeRemaining * 1000} renderer={rendererSecondes} />
                          </p>
                          <span>secs</span>
                        </div>
                      </div>
                    )}

                    <div className={Style.bigNFTSlider_box_left_sliderBtn}>
                      <TbArrowBigLeftLines
                        className={Style.bigNFTSlider_box_left_sliderBtn_icon}
                        onClick={() => dec()}
                      />
                      <TbArrowBigRightLine
                        className={Style.bigNFTSlider_box_left_sliderBtn_icon}
                        onClick={() => inc()}
                      />
                    </div>
                  </div>


                </div>
                <div className={Style.bigNFTSlider_box_right}>
                  <div className={Style.bigNFTSlider_box_right_box}>

                    <h2>SHAMBLES: {nftList[idNumber][3]}</h2>

                    <Image
                      src={uri[idNumber]}
                      alt="NFT IMAGE"
                      className={Style.bigNFTSlider_box_right_box_img}
                      width={350}
                      height={350}
                    />
                  </div>
                </div>
              </div>
            </div>

          </div>
        ) : (
          <Alert status='warning' width="50%">
            <AlertIcon />
            Please, connect your Wallet!
          </Alert>
        )}
      </Layout>
    </>
  )
}
